' Generated by archive-service.ps1 - do not edit by hand.
' Purpose: start the archive backend with a fully hidden window (style 0), so
' that logging on does not flash a black console. Also wraps it so the backend
' keeps its own log file. NOTE: this file is ASCII-only on purpose - wscript
' reads .vbs in the system ANSI code page, so non-ASCII here would garble.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "E:\deepseek\RhineLabUI"
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & "E:\deepseek\RhineLabUI\scripts\archive-service.ps1" & Chr(34) & " -Action run", 0, False
